name: WASM Build (FNA)

on: 
  push:
    branches: 
      - master
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
      
jobs:
  windows:
    strategy:
      matrix:
        os: [ubuntu-18.04]
        variant: [Release]
    runs-on: ${{ matrix.os }}
    name: WASM ${{ matrix.variant }} on ${{ matrix.os }}
    steps:
      - name: Check out source
        uses: actions/checkout@v1
      - uses: mymindstorm/setup-emsdk@v7
      - name: Verify
        run: emcc -v    
      - name: Check working directory
        shell: bash
        run: |
          pwd
      - name: SDL2    
        shell: bash
        run: |
          git clone https://github.com/libsdl-org/SDL
          cd SDL
          mkdir emscripten-build
          cd emscripten-build
          emconfigure ../configure --host=wasm32-unknown-emscripten --disable-assembly --disable-threads --disable-cpuinfo CFLAGS="-O2 -Wno-warn-absolute-paths -Wdeclaration-after-statement -Werror=declaration-after-statement" --prefix="$PWD/emscripten-sdl2-installed"
          emmake make
          emmake make install
      - name: FNA3D
        shell: bash
        run: |         
          git clone --recursive https://github.com/FNA-XNA/FNA3D
          cd FNA3D
          mkdir build
          cd build
          emcmake cmake .. -DSDL2_INCLUDE_DIRS=/home/runner/work/FNA-WASM-Build/FNA-WASM-Build/SDL/include -DSDL2_LIBRARIES=/home/runner/work/FNA-WASM-Build/FNA-WASM-Build/SDL/emscripten-build/emscripten-sdl2-installed/lib/libSDL2.a
          emmake make
      - name: FAudio
        shell: bash
        run: |           
          git clone https://github.com/FNA-XNA/FAudio
          cd FAudio
          mkdir build
          cd build
          emcmake cmake .. -DSDL2_INCLUDE_DIRS=/home/runner/work/FNA-WASM-Build/FNA-WASM-Build/SDL/include -DSDL2_LIBRARIES=/home/runner/work/FNA-WASM-Build/FNA-WASM-Build/SDL/emscripten-build/emscripten-sdl2-installed/lib/libSDL2.a
          emmake make
      - name: Copy Binaries (with new names)
        shell: bash
        run: |
          mkdir Binaries
          cp ./SDL/emscripten-build/emscripten-sdl2-installed/lib/libSDL2.a Binaries/SDL2.a
          cp ./FNA3D/build/libFNA3D.a Binaries/FNA3D.a
          cp ./FNA3D/build/libmojoshader.a Binaries/libmojoshader.a    
          cp ./FAudio/build/libFAudio.a Binaries/FAudio.a
          7z a FNA-WASM.Binaries.zip Binaries/*
      - name: Archive ${{ matrix.variant }} WASM archive on ${{ matrix.os }}
        uses: actions/upload-artifact@master
        with:
          name: WASM Libraries for ${{ matrix.variant }} on ${{ matrix.os }}
          path: FNA-WASM.Binaries.zip  
